DATASET:
    NAME: "cityscape"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 300
    BATCH_SIZE: 2
    CROP_SIZE: 769
TEST:
    BATCH_SIZE: 2
    CROP_SIZE: (1025, 2049)
#    TEST_MODEL_PATH: trained_models/deeplabv3_plus_xception_segmentron.pth

SOLVER:
    LR: 0.01

MODEL:
    MODEL_NAME: "PointRend"
    BACKBONE: "resnet101c"
    BN_EPS_FOR_ENCODER: 1e-3
    DEEPLABV3_PLUS:
        ENABLE_DECODER: False