DATASET:
    NAME: "transparent11"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
TRAIN:
    EPOCHS: 50
    BATCH_SIZE: 4
    CROP_SIZE: (512, 512)
    BASE_SIZE: 512
    MODEL_SAVE_DIR: 'workdirs/trans10kv2/trans2seg_tiny2'
TEST:
    BATCH_SIZE: 16
    CROP_SIZE: (512, 512)

SOLVER:
    OPTIMIZER: "adam"
    LR: 0.0001
MODEL:
    MODEL_NAME: "Trans2Seg"
    BACKBONE: "resnet50c"
    TRANS2Seg:
        embed_dim: 128
        depth: 2
        num_heads: 4
        mlp_ratio: 3.
        hid_dim: 48

AUG:
    CROP: False